import time
import os

print("Note: Please RUN File as administrator")
print("Loading")
time.sleep(2)
os.system("cls")
print("--------------------------------------")
print()
print("     SPEED UP   BY AYMAN BOURAAMANE   ")
print()
print("--------------------------------------")
print()
input = input("Type Any word to start!")
print(input)
print("Delete the cache and thumbnail folders")
os.system("rm -rf ~/.cache")
os.system("rm -rf ~/.thumbs")
os.system("cls")
print("Delete the cache and thumbnail folders (DONE)")
print("Delete the temporary files")
os.system("sudo apt autoclean && sudo apt clean && sudo apt autoremove")
os.system("cls")
print("Delete the cache and thumbnail folders (DONE")
print("Delete the temporary files (DONE)")
time.sleep(2)

os.system(cls)
print("Terminal will close in 3")
os.system("cls")
time.sleep(0.5)
print("Terminal will close in 2")
os.system("cls")
time.sleep(0.5)
print("Terminal will close in 1")
os.system("cls")
time.sleep(0.5)
exit()


